version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "183295452329"  # Replace with your AWS account ID
    AWS_REGION: "us-east-1"              # Replace with your AWS region (e.g., us-east-1)
    ECR_REPOSITORY: "my-tomcat-app"          # Replace with your ECR repository name
    IMAGE_TAG: "latest"                      # Docker image tag
    ECS_CLUSTER: "my-tomcat-cluster"         # Replace with your ECS cluster name
    ECS_SERVICE: "my-tomcat-service"         # Replace with your ECS service name
    TASK_DEFINITION: "my-farget-task"        # Replace with your ECS task definition name

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y docker.io jq
      - sudo apt update -y
      - sudo apt upgrade -y
      - sudo apt install unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
      - echo "Updating ECS task definition..."
      - TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition $TASK_DEFINITION --region $AWS_REGION | jq -r '.taskDefinition.taskDefinitionArn')
      - echo "Task Definition ARN: $TASK_DEFINITION_ARN"
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_DEFINITION --region $AWS_REGION --force-new-deployment

artifacts:
  files:
    - '**/*' 
